//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstEFHWsol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BirdsEntities : DbContext
    {
        public BirdsEntities()
            : base("name=BirdsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bird> Birds { get; set; }
        public virtual DbSet<BirdCount> BirdCounts { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
    }
}
