//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstEFHWsol
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirdCount
    {
        public int CountID { get; set; }
        public string RegionID { get; set; }
        public int BirderID { get; set; }
        public string BirdID { get; set; }
        public System.DateTime CountDate { get; set; }
        public int Counted { get; set; }
    
        public virtual Bird Bird { get; set; }
        public virtual Region Region { get; set; }
    }
}
